version: '3'
services:
  jenkins:
    #image: jenkins/jenkins:2.332.2-lts
    image: jenkins-docker:latest
    restart: unless-stopped
    hostname: jenkins
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      # - /usr/bin/docker:/usr/local/bin/docker
      - /home/ubuntu/accdetails:/opt/accdetails
    ports:
      - 8081:8080
      - 50000:50000
